# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0004_auto_20160210_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionmodel',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
