# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0008_auto_20160211_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxtact', models.FloatField()),
                ('free_resource', models.FloatField()),
                ('medium', models.FloatField()),
                ('dispersion', models.FloatField()),
                ('lawstring', models.CharField(choices=[('square', 'square'), ('current', 'current'), ('ratio', 'ratio'), ('linear', 'linear'), ('cubic', 'cubic'), ('sign', 'sign')], default='square', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.FloatField()),
                ('start_time', models.FloatField()),
                ('lifetime', models.FloatField()),
                ('duration', models.FloatField()),
                ('action', models.TextField()),
                ('object_type', models.TextField()),
                ('distance', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('row', models.FloatField()),
                ('tact', models.FloatField()),
                ('num', models.IntegerField()),
                ('precedence', models.FloatField()),
                ('catastrophe', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='RequisitionModel',
        ),
    ]
