# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0009_auto_20160212_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('current', 'current'), ('square', 'square'), ('sign', 'sign'), ('ratio', 'ratio'), ('linear', 'linear'), ('cubic', 'cubic')], default='current', max_length=255),
        ),
    ]
