# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0010_auto_20160215_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('square', 'square'), ('cubic', 'cubic'), ('sign', 'sign'), ('linear', 'linear'), ('current', 'current'), ('ratio', 'ratio')], default='square', max_length=255),
        ),
    ]
