# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0012_auto_20160215_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionoutput',
            name='first',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionoutput',
            name='fourth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionoutput',
            name='second',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionoutput',
            name='third',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('cubic', 'cubic'), ('sign', 'sign'), ('square', 'square'), ('current', 'current'), ('linear', 'linear'), ('ratio', 'ratio')], default='cubic', max_length=255),
        ),
    ]
