# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0013_auto_20160215_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionoutput',
            old_name='first',
            new_name='numinbarrier',
        ),
        migrations.RemoveField(
            model_name='requisitionoutput',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='requisitionoutput',
            name='second',
        ),
        migrations.RemoveField(
            model_name='requisitionoutput',
            name='third',
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('square', 'square'), ('ratio', 'ratio'), ('linear', 'linear'), ('sign', 'sign'), ('current', 'current'), ('cubic', 'cubic')], default='square', max_length=255),
        ),
    ]
