# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0014_auto_20160215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('sign', 'sign'), ('linear', 'linear'), ('square', 'square'), ('cubic', 'cubic'), ('current', 'current'), ('ratio', 'ratio')], default='sign', max_length=255),
        ),
    ]
