# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0016_auto_20160219_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionoutput',
            name='tfirst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('sign', 'sign'), ('cubic', 'cubic'), ('linear', 'linear'), ('current', 'current'), ('square', 'square'), ('ratio', 'ratio')], default='sign', max_length=255),
        ),
    ]
