# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0017_auto_20160219_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('sign', 'sign'), ('cubic', 'cubic'), ('square', 'square'), ('ratio', 'ratio'), ('current', 'current'), ('linear', 'linear')], default='sign', max_length=255),
        ),
    ]
