# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0018_auto_20160219_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('ratio', 'ratio'), ('sign', 'sign'), ('linear', 'linear'), ('square', 'square'), ('current', 'current'), ('cubic', 'cubic')], default='ratio', max_length=255),
        ),
    ]
