# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0019_auto_20160229_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcAndClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch', models.BooleanField()),
                ('toclear', models.BooleanField()),
                ('graph_x', models.CharField(choices=[('num', 'number'), ('action', 'Action'), ('object_type', 'Object'), ('arrival_time', 'Arrival time'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='num', max_length=255)),
                ('graph_y', models.CharField(choices=[('num', 'number'), ('action', 'Action'), ('object_type', 'Object'), ('arrival_time', 'Arrival time'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='Action', max_length=255)),
                ('graph_type', models.CharField(choices=[('scatter', 'XY Scatter'), ('pie', 'Pie Chart')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('current', 'current'), ('linear', 'linear'), ('sign', 'sign'), ('ratio', 'ratio'), ('square', 'square'), ('cubic', 'cubic')], default='current', max_length=255),
        ),
    ]
