# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0022_auto_20160301_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcandclear',
            name='toclear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('cubic', 'cubic'), ('sign', 'sign'), ('current', 'current'), ('square', 'square'), ('ratio', 'ratio'), ('linear', 'linear')], default='cubic', max_length=255),
        ),
    ]
