# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0024_auto_20160301_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('sign', 'sign'), ('linear', 'linear'), ('square', 'square'), ('ratio', 'ratio'), ('cubic', 'cubic'), ('current', 'current')], default='sign', max_length=255),
        ),
    ]
