# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0025_auto_20160302_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionoutput',
            name='cb',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_x',
            field=models.CharField(choices=[('num', 'number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('arrival_time', 'Arrival time'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='num', max_length=255),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_y',
            field=models.CharField(choices=[('num', 'number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('arrival_time', 'Arrival time'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='cb', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('current', 'current'), ('ratio', 'ratio'), ('sign', 'sign'), ('linear', 'linear'), ('square', 'square'), ('cubic', 'cubic')], default='current', max_length=255),
        ),
    ]
