# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0026_auto_20160303_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('linear', 'linear'), ('current', 'current'), ('sign', 'sign'), ('ratio', 'ratio'), ('cubic', 'cubic'), ('square', 'square')], default='linear', max_length=255),
        ),
    ]
