# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0027_auto_20160307_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='category',
            field=models.CharField(choices=[('num', 'number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('arrival_time', 'Arrival time'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='num', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('ratio', 'ratio'), ('square', 'square'), ('sign', 'sign'), ('current', 'current'), ('linear', 'linear'), ('cubic', 'cubic')], default='ratio', max_length=255),
        ),
    ]
