# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElfenLied', '0030_auto_20160321_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionoutput',
            name='arrival_time',
        ),
        migrations.AlterField(
            model_name='graph',
            name='category',
            field=models.CharField(choices=[('num', 'number'), ('observing_num', 'observe number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='num', max_length=255),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_x',
            field=models.CharField(choices=[('num', 'number'), ('observing_num', 'observe number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='num', max_length=255),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_y',
            field=models.CharField(choices=[('num', 'number'), ('observing_num', 'observe number'), ('cb', 'cb'), ('action', 'Action'), ('object_type', 'Object'), ('start_time', 'Start time'), ('lifetime', 'Lifetime'), ('duration', 'Duration'), ('precedence', 'Precedence'), ('catastrophe', 'Catastrophe'), ('direction', 'direction'), ('tfirst', 'Tfirst'), ('distance', 'Distance'), ('azimuth', 'Azimuth'), ('row', 'Row'), ('tact', 'Tact')], default='observe number', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitioninput',
            name='lawstring',
            field=models.CharField(choices=[('linear', 'linear'), ('current', 'current'), ('sign', 'sign'), ('square', 'square'), ('ratio', 'ratio'), ('cubic', 'cubic')], default='linear', max_length=255),
        ),
    ]
